# Security related configuration, e.g. default credentials
security:
  # Security configuration for webEngine
  webEngine:
    # Credentials for the WebEngine Server administrative user
    # Note: Be aware of the out-of-the-box additional "admin1" adminsitrative user
    # Also, be aware that if we want to use custom-secrets, we must also unset webEngineUser & webEnginePassword values
    webEngineUser: ""
    webEnginePassword: ""
    customWebEngineSecret: "web-engine-secret" # secret only is taken if previous values are empty.

pod:
    webEngine:
    - name: JVM_ARGS
      value: >-
        -Dcom.sun.jndi.ldap.connect.pool.protocol="plain ssl"
        -Dcom.sun.jndi.ldap.connect.pool.timeout=180000
        -Dcom.sun.jndi.ldap.connect.pool.maxsize=50
        -Dcom.sun.jndi.ldap.connect.pool.prefsize=10
        -Dcom.sun.jndi.ldap.connect.pool.initsize=5

# Logging & Trace configuration
logging:
  webEngine:
    level:
      - "*=info" # Global default log level
      - "com.ibm.wps.logging.ExceptionLogger=all" # ExceptionLogger default level
      - "hcl.logging.search-v2.DEBUG.client.*=all" # Search Debugging
      - "com.ibm.ws.security.*=all" # Requerido por Thorsten para SSL/Auth
      - "com.ibm.ws.webcontainer.security.*=all" # Requerido por Thorsten para contexto we

configuration:
  containerTimezone: "Europe/Madrid"
  webEngine:
    customTruststoreSecrets:
      ca-secret-1: "dx-custom-certs"
    customSecrets:
      ldap-credentials: "ldap-credentials"
 
    configOverrideFiles:
      user-overrides.xml: |
          <server description="DX Web Engine server">
          <basicRegistry id="basic" realm="defaultWIMFileBasedRealm">
          <user name="wpsadmin" password="Passw0rd" id="uid=wpsadmin,o=defaultWIMFileBasedRealm" />
          <user name="admin1" password="admin2pwd" id="uid=admin1,o=defaultWIMFileBasedRealm"/>
          <group name="wpsadmins" id="cn=wpsadmins,o=defaultWIMFileBasedRealm">
             <member name="andres"/>
             <member name="wpsadmin" />
          </group>
          </basicRegistry>
          </server>
      ldapOverride.xml: |
          <server description="WebEngineServer">
            <ldapRegistry id="ldap" realm="SampleLdapIDSRealm"
              host="ldap.europesip-lab.com" port="636" ignoreCase="true"
              baseDN="dc=europesip,dc=com"
              ldapType="Custom"
              sslEnabled="true"
              sslRef="customSSLConfig"
              bindDN="${LDAP_USERNAME}"
              bindPassword="${LDAP_PASSWORD}">

              <customFilters
                userFilter="(&amp;(|(uid=%v)(mail=%v))(objectclass=inetOrgPerson))"
                groupFilter="(&amp;(cn=%v)(|(objectclass=groupOfNames)(objectclass=groupOfUniqueNames)))"
                userIdMap="*:uid"
                groupIdMap="*:cn"
                groupMemberIdMap="ibm-allGroups:member;ibm-allGroups:uniqueMember;groupOfNames:member;groupOfUniqueNames:uniqueMember">
              </customFilters>

              <attributeConfiguration>
                <attribute name="mail" propertyName="ibm-primaryEmail" entityType="PersonAccount"/>
                <attribute name="title" propertyName="ibm-jobTitle" entityType="PersonAccount"/>
              </attributeConfiguration>

            </ldapRegistry>
            <federatedRepository>
               <primaryRealm name="FederatedRealm" allowOpIfRepoDown="true">
                  <participatingBaseEntry name="o=defaultWIMFileBasedRealm"/>
                  <participatingBaseEntry name="dc=europesip,dc=com"/>
               </primaryRealm>
            </federatedRepository>
          </server>
