/****************************************************************************************************
 * SCRIPT 2: ASIGNACIÓN DE PERMISOS Y ROLES
 * OBJETIVO: Otorgar privilegios a los roles y asignar dichos roles a los usuarios creados.
 * * ★★★★★ IMPORTANT WARNING ★★★★★
 * Execute this script AFTER "01_Creacion_Infraestructura.sql".
 * Modify <replace-with-user> matches the user created in the previous script.
 ****************************************************************************************************/

--------------------------------------------------------------
-- 1. GRANTS TO ROLES (System Privileges)
--------------------------------------------------------------

-- WP_BASE_CONFIG_USERS Permissions
GRANT ALTER ANY TABLE, CREATE ANY TABLE, DROP ANY TABLE,
	CREATE ANY INDEX, DROP ANY INDEX,
	INSERT ANY TABLE, UPDATE ANY TABLE, SELECT ANY TABLE, DELETE ANY TABLE,
	CREATE SESSION
	TO WP_BASE_CONFIG_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_BASE_CONFIG_USERS;
GRANT SELECT ANY SEQUENCE, DROP ANY SEQUENCE TO WP_BASE_CONFIG_USERS;

-- WP_BASE_RUNTIME_USERS Permissions
GRANT CREATE SESSION TO WP_BASE_RUNTIME_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_BASE_RUNTIME_USERS;
GRANT SELECT ANY SEQUENCE, DROP ANY SEQUENCE TO WP_BASE_RUNTIME_USERS; 

-- WP_JCR_CONFIG_USERS Permissions
GRANT ALTER ANY TABLE, CREATE ANY TABLE, DROP ANY TABLE,
	CREATE ANY INDEX, DROP ANY INDEX,
	INSERT ANY TABLE, UPDATE ANY TABLE, SELECT ANY TABLE, DELETE ANY TABLE,
	CREATE SESSION
	TO WP_JCR_CONFIG_USERS;
GRANT CREATE TABLESPACE, DROP TABLESPACE,
	CREATE ANY SEQUENCE, DROP ANY SEQUENCE,
	CREATE ANY TRIGGER, DROP ANY TRIGGER,
	CREATE ANY TYPE, DROP ANY TYPE, EXECUTE ANY TYPE,
	CREATE ANY VIEW, DROP ANY VIEW
	TO WP_JCR_CONFIG_USERS;
GRANT SELECT ON DBA_IND_COLUMNS to WP_JCR_CONFIG_USERS;
GRANT SELECT ON DBA_INDEXES to WP_JCR_CONFIG_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_JCR_CONFIG_USERS;

-- WP_JCR_RUNTIME_USERS Permissions
GRANT CREATE SESSION TO WP_JCR_RUNTIME_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_JCR_RUNTIME_USERS;

-- WP_PZN_CONFIG_USERS Permissions
GRANT ALTER ANY TABLE, CREATE ANY TABLE, DROP ANY TABLE,
	CREATE ANY INDEX, DROP ANY INDEX,
	INSERT ANY TABLE, UPDATE ANY TABLE, SELECT ANY TABLE, DELETE ANY TABLE,
	CREATE SESSION
	TO WP_PZN_CONFIG_USERS;
GRANT CREATE ANY SEQUENCE, DROP ANY SEQUENCE TO WP_PZN_CONFIG_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_PZN_CONFIG_USERS;

-- WP_PZN_RUNTIME_USERS Permissions
GRANT CREATE SESSION TO WP_PZN_RUNTIME_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_PZN_RUNTIME_USERS;


--------------------------------------------------------------
-- 2. ASSIGN ROLES TO USERS & QUOTAS
--------------------------------------------------------------

-- Grant Unlimited Tablespace to Schemas
GRANT UNLIMITED TABLESPACE TO release;
GRANT UNLIMITED TABLESPACE TO community;
GRANT UNLIMITED TABLESPACE TO customization;
GRANT UNLIMITED TABLESPACE TO jcr;
GRANT UNLIMITED TABLESPACE TO feedback;
GRANT UNLIMITED TABLESPACE TO likeminds;

-- Technical User Grants (Connection User)
GRANT DBA TO <replace-with-user>;
GRANT WP_BASE_CONFIG_USERS TO <replace-with-user>;
GRANT WP_BASE_RUNTIME_USERS TO <replace-with-user>;
GRANT WP_JCR_CONFIG_USERS TO <replace-with-user>;
GRANT WP_JCR_RUNTIME_USERS TO <replace-with-user>;
GRANT WP_PZN_CONFIG_USERS TO <replace-with-user>;
GRANT WP_PZN_RUNTIME_USERS TO <replace-with-user>;

--------------------------------------------------------------
-- 3. SPECIFIC JCR TABLESPACE USAGE
-- Grants for the JCR config group to use specific tablespaces
--------------------------------------------------------------
-- Note: Ensure these tablespaces exist (created in Script 1)
-- Check if CMBINV04 and ICMLSUSRTSPACE4 exist in your environment or remove if not needed.
-- Based on standard script, only ICMLFQ32, ICMLNF32, ICMVFQ04, ICMSFQ04, ICMLSNDX are explicitly created.

GRANT USE OF TABLESPACE ICMLFQ32 TO WP_JCR_CONFIG_USERS;
GRANT USE OF TABLESPACE ICMLNF32 TO WP_JCR_CONFIG_USERS;
GRANT USE OF TABLESPACE ICMVFQ04 TO WP_JCR_CONFIG_USERS;
GRANT USE OF TABLESPACE ICMSFQ04 TO WP_JCR_CONFIG_USERS;
-- GRANT USE OF TABLESPACE CMBINV04 TO WP_JCR_CONFIG_USERS;      -- Uncomment if exists
-- GRANT USE OF TABLESPACE ICMLSUSRTSPACE4 TO WP_JCR_CONFIG_USERS; -- Uncomment if exists
