images:
  # Container repository used to retrieve the images
  repository: "image-registry.openshift-image-registry.svc:5000/openshift"
  
  # Image name for each application
  names:
    contentComposer: "dx-content-composer"
    core: "dx-core"
    damPluginGoogleVision: "dx-dam-plugin-google-vision"
    digitalAssetManagement: "dx-digital-asset-manager"
    imageProcessor: "dx-image-processor"
    openLdap: "dx-openldap"
    persistenceConnectionPool: "dx-persistence-connection-pool"
    persistenceNode: "dx-persistence-node"
    persistenceMetricsExporter: "dx-persistence-metrics-exporter"
    remoteSearch: "dx-remote-search"
    ringApi: "dx-ringapi"
    runtimeController: "dx-runtime-controller"
    loggingSidecar: "dx-logging-sidecar"
    haproxy: "dx-haproxy"
    damPluginKaltura: "dx-dam-plugin-kaltura"
    licenseManager: "dx-license-manager"
    prereqsChecker: "dx-prereqs-checker"
    webEngine: "dx-webengine"

# Persistent Volume Setup
volumes:
  digitalAssetManagement:
    # Binary storage PVC, shared by all Digital Asset Management Pods - RWX
    binaries:
      storageClassName: "dx-deploy-rwx"
  # Persistent Volumes for Persistence Node
  persistenceNode:
    # Database PVC, one per Persistence Node
    database:
      storageClassName: "dx-deploy-rwo"
  # Persistent Volumes for License-Manager Node
  licenseManager:
    # Database PVC, one per license-manager Node
    data:
      storageClassName: "dx-deploy-rwo"
  # Persistent Volumes for webEngine
  webEngine:
    # Customization PVC one per webEngine pod - RWO
    customization:
      storageClassName: "dx-deploy-rwo"
    # Application Log PVC, one per webEngine pod - RWO
    log:
      storageClassName: "dx-deploy-rwo"

# Controls which application is deployed and configured
applications:
  # Deploy Open LDAP (set to false for external LDAP)
  openLdap: false
  # Deploys the Remote Search
  remoteSearch: false
  # Do not install Core DX, install WebEngine (Compose) instead
  core: false
  # Install Compose
  webEngine: true

# Configuration for the peopleservice sub-chart.
# Set `enabled` to `true` to enable the peopleservice sub-chart, or `false` to disable it.
peopleservice:
  enabled: false 
  
# Networking specific configuration
networking:
  # Networking configurations specific to HAProxy
  haproxy:
    # Configuration to set the type Service type for the HAProxy Service
    serviceType: "ClusterIP"
  # TLS Certificate secret used for HAProxy
  tlsCertSecret: "dx-tls-cert"
  # Networking configuration specific to webEngine
  webEngine:
    # Host of webEngine, must be specified as a FQDN
    host: "dx.apps.promox.europesip-lab.com"

# Security related configuration, e.g. default credentials
security:
  # Security configuration for webEngine
  webEngine:
    # Credentials for the WebEngine Server administrative user
    # Note: Be aware of the out-of-the-box additional "admin1" adminsitrative user
    # Also, be aware that if we want to use custom-secrets, we must also unset webEngineUser & webEnginePassword values
    webEngineUser: null
    webEnginePassword: null
    customWebEngineSecret: "web-engine-secret" # secret only is taken if previous values are empty.


configuration:
  containerTimezone: "Europe/Madrid"
  webEngine:
    customTruststoreSecrets:
      ca-secret-1: "dx-custom-certs"
    # Use a External Database, avoid Derby
    useExternalDatabase: true
    # The secrets below contains the info about the database tables to use 
    # customDbTypePropertiesSecret: custom-credentials-webengine-dbtype-secret
    # Do not USE Secrets for DbtypeProperties, since is not well documented and we do not know how to use it 
    # customDbDomainPropertiesSecret: custom-credentials-webengine-dbdomain-secret
    # If true, existing WebEngine database tables will be dropped and re-created whenever database transfer is run.
    dropDatabaseTables: true
    #
    dbDomainProperties:
      InitializeFeedbackDB: "true"
      feedback.DbType: "oracle"
      feedback.DbName: "feedback"
      feedback.DbSchema: "feedback"
      feedback.DataSourceName: "wpfdbkdbDS"
      feedback.DbUrl: "jdbc:oracle:thin:@//oracle.europesip-lab.com:1521/WPSDB"
      feedback.DbUser: "wpsuser"
      feedback.DbPassword: "Passw0rd"
      feedback.DbRuntimeUser: "wpsuser"
      feedback.DbRuntimePassword: "Passw0rd"
      feedback.DBA.DbUser: "wpsuser"
      feedback.DBA.DbPassword: "Passw0rd"
      feedback.DbConfigRoleName: "WP_PZN_CONFIG_USERS"
      feedback.DbRuntimeRoleName: "WP_PZN_RUNTIME_USERS"
      feedback.XDbName: "WPFDBK"
      feedback.DbNode: "pznNode"
      likeminds.DbType: "oracle"
      likeminds.DbName: "likeminds"
      likeminds.DbSchema: "likeminds"
      likeminds.DataSourceName: "wplmdbDS"
      likeminds.DbUrl: "jdbc:oracle:thin:@//oracle.europesip-lab.com:1521/WPSDB"
      likeminds.DbUser: "wpsuser"
      likeminds.DbPassword: "Passw0rd"
      likeminds.DbRuntimeUser: "wpsuser"
      likeminds.DbRuntimePassword: "Passw0rd"
      likeminds.DBA.DbUser: "wpsuser"
      likeminds.DBA.DbPassword: "Passw0rd"
      likeminds.DbConfigRoleName: "WP_PZN_CONFIG_USERS"
      likeminds.DbRuntimeRoleName: "WP_PZN_RUNTIME_USERS"
      likeminds.XDbName: "WPLM"
      likeminds.DbNode: "pznNode"
      release.DbType: "oracle"
      release.DbName: "release"
      release.DbSchema: "release"
      release.DataSourceName: "wpreldbDS"
      release.DbUrl: "jdbc:oracle:thin:@//oracle.europesip-lab.com:1521/WPSDB"
      release.DbUser: "wpsuser"
      release.DbPassword: "Passw0rd"
      release.DbRuntimeUser: "wpsuser"
      release.DbRuntimePassword: "Passw0rd"
      release.DBA.DbUser: "wpsuser"
      release.DBA.DbPassword: "Passw0rd"
      release.DbConfigRoleName: "WP_BASE_CONFIG_USERS"
      release.DbRuntimeRoleName: "WP_BASE_RUNTIME_USERS"
      release.XDbName: "WPREL"
      release.DbNode: "wpsNode"
      community.DbType: "oracle"
      community.DbName: "community"
      community.DbSchema: "community"
      community.DataSourceName: "wpcommdbDS"
      community.DbUrl: "jdbc:oracle:thin:@//oracle.europesip-lab.com:1521/WPSDB"
      community.DbUser: "wpsuser"
      community.DbPassword: "Passw0rd"
      community.DbRuntimeUser: "wpsuser"
      community.DbRuntimePassword: "Passw0rd"
      community.DBA.DbUser: "wpsuser"
      community.DBA.DbPassword: "Passw0rd"
      community.DbConfigRoleName: "WP_BASE_CONFIG_USERS"
      community.DbRuntimeRoleName: "WP_BASE_RUNTIME_USERS"
      community.XDbName: "WPCOMM"
      community.DbNode: "wpsNode"
      customization.DbType: "oracle"
      customization.DbName: "WPCUST"
      customization.DbSchema: "customization"
      customization.DataSourceName: "wpcustdbDS"
      customization.DbUrl: "jdbc:oracle:thin:@//oracle.europesip-lab.com:1521/WPSDB"
      customization.DbUser: "wpsuser"
      customization.DbPassword: "Passw0rd"
      customization.DbRuntimeUser: "wpsuser"
      customization.DbRuntimePassword: "Passw0rd"
      customization.DBA.DbUser: "wpsuser"
      customization.DBA.DbPassword: "Passw0rd"
      customization.DbConfigRoleName: "WP_BASE_CONFIG_USERS"
      customization.DbRuntimeRoleName: "WP_BASE_RUNTIME_USERS"
      customization.XDbName: "WPCUST"
      customization.DbNode: "wpsNode"
      jcr.DbType: "oracle"
      jcr.DbName: "jcr"
      jcr.DbSchema: "jcr"
      jcr.DataSourceName: "wpjcrdbDS"
      jcr.DbUrl: "jdbc:oracle:thin:@//oracle.europesip-lab.com:1521/WPSDB"
      jcr.DbUser: "wpsuser"
      jcr.DbPassword: "Passw0rd"
      jcr.DbRuntimeUser: "wpsuser"
      jcr.DbRuntimePassword: "Passw0rd"
      jcr.DBA.DbUser: "wpsuser"
      jcr.DBA.DbPassword: "Passw0rd"
      jcr.DbConfigRoleName: "WP_JCR_CONFIG_USERS"
      jcr.DbRuntimeRoleName: "WP_JCR_RUNTIME_USERS"
      jcr.XDbName: "WPJCR"
      jcr.DbNode: "wpsNode"
    dbTypeProperties:
      oracle.DbDriver: "oracle.jdbc.driver.OracleDriver"
      oracle.DbLibrary: "/opt/openliberty/wlp/usr/svrcfg/templates/jars/oracle/ojdbc11.jar:/opt/openliberty/wlp/usr/svrcfg/templates/jars/oracle/xdb6-11.2.0.4.jar"
      oracle.JdbcProviderName: "wpdbJDBC_oracle"
